

source "https://rubygems.org"

gem "net-smtp", "~> 0.5"
gem "pony",     "~> 1.13"
gem "puma",     "~> 7.0"
gem "sinatra",  "~> 4.1"

gem "opentelemetry-sdk", "~> 1.4.1"
gem "opentelemetry-exporter-otlp", "~> 0.26.3"
gem "opentelemetry-instrumentation-all", "~> 0.60.0"
